baseURL = "https://sebastiankindl.at/"
languageCode = "en"
title = "sebastian kindl"
theme = "PaperMod"
defaultContentLanguage = "en"
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 10

# Blog-URLs
[permalinks]
  blog = "/blog/:slug/"

[params]
  description = "Portfolio of Sebastian Kindl"
  author = "Sebastian Kindl"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowWordCount = true
  ShowToc = true
  customCSS = ["css/profile.css"]

  # Profile
  [params.profileMode]
    enabled = true
    title = "Sebastian Kindl"
    subtitle = "Technical Physics graduate with a strong quantitative foundation in modeling, data analysis, and problem-solving. Experienced in machine learning and advanced analytics, with a proven ability to translate technical concepts into scalable, data-driven solutions for business, strategy, and decision-making."
    imageUrl = "/photo.png"        # optional
    imageTitle = "Sebastian"
    imageWidth = 180
    imageHeight = 250
    buttons = [
#      { name = "projects", url = "/projects/" },
      { name = "thesis", url = "/thesis/" },
      { name = "curriculum Vitae", url = "/cv/" },
      { name = "contact", url = "/contact/" }
    ]

  [params.homeInfoParams]
    Title = ""
    Content = "Technical Physics @ TU Wien • ML/AI • Computational Materials. Thesis highlights, projects, and notes."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sebastiankindl"

  [[params.socialIcons]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/sebastiankindl/"

  [[params.socialIcons]]
    name = "whatsapp"
    url = "https://wa.me/436644159165"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:sebastian.kindl@outlook.com"

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
#  [[menu.main]]
#    name = "projects"
#    url = "/projects/"
#    weight = 2
  [[menu.main]]
    name = "thesis"
    url ="/thesis/"
    weight = 3
  [[menu.main]]
    name = "curriculum vitae"
    url = "/cv/"
    weight = 4
  [[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 5

[outputs]
  home = ["HTML","RSS","JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
